sudo: false

# These directories are cached to S3 at the end of the build.
cache:
  directories:
    - $HOME/.ivy/cache
    - $HOME/.sbt/boot

language: scala

#script:
#  - sbt ++$TRAVIS_SCALA_VERSION -Dfile.encoding=UTF8 -J-XX:ReservedCodeCacheSize=256M test

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

jdk:
  - oraclejdk8

scala:
  - 2.10.7
  - 2.11.12
  - 2.12.8
